### ISSUE TITLE
Gaia Mobile App - not connecting

### ISSUE THREAD

**Issue by dom-madrid** [gaiaehr/gaiaehr#2]
Hi,
Testing on Samsung Galaxy S2
Test setup Ubuntu 14.04 Server + Gaiaehr 0.7
Accessing the logon page only http://localhost/gaiaehr, returns a grey page (not white)
Accessing the logon page through the mobile page http://localhost/gaiaehr/_aire returns the following error:
![screenshot_2014-05-10-19-49-57](https://cloud.githubusercontent.com/assets/5640062/2936735/9c2142d8-d86e-11e3-8c5f-492cab00387a.png)
URL is correct, the key associated as well. No other configuration available...

**Comment by hrivera787** [comment]
Transferred the issue to: https://gaiaehr.atlassian.net/browse/GAIAEH-360?jql=project%20%3D%20%22GAIAEH%22%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC
