### ISSUE TITLE
Change in locale - no effect

### ISSUE THREAD

**Issue by dom-madrid** [gaiaehr/gaiaehr#3]
Hi,
Test Env: Ubuntu 14.04 server +  Gaiaehr 0.7
Changing the folowing locale in the database have partial or no effect in the app:
Time Display Format: from g:i a to H:i (3:00 pm to 15:00) -> no impact in dashboard, no impact in adding event, time of birth, New encounter,...
Date Display format from Y-m-d to d-m-Y: Partial change. No change in DOB, New encounter
Decimal point: from (.) to (,): In new payment: does not accept the comma.

**Comment by hrivera787** [comment]
Hi sorry for the late response.

We usually don't use this bug tracking system.
You can follow us on: https://gaiaehr.atlassian.net/secure/Dashboard.jspa

I will transfer this issue to there.
