### ISSUE TITLE
Navigation Pane disorder for Jr Admin, Referrer

### ISSUE THREAD

**Issue by yemikudaisi** [gaiaehr/gaiaehr#47]
When a user logs-in with assigned role of junior admin or referrer the tree view in the navigation pane is distorted. See snapshots below.

Jr Admin
![jr-admin](https://cloud.githubusercontent.com/assets/3257276/5775765/d25dd9d0-9d7e-11e4-863f-d5c138463119.png)
 
Referrer
![referrer](https://cloud.githubusercontent.com/assets/3257276/5775770/e1009716-9d7e-11e4-84ee-fd6d925f98b7.png)

**Comment by andrewbhandari** [comment]
what version you using ?

**Comment by vela1606** [comment]
Working on this as I write :-)

**Comment by vela1606** [comment]
Fixed -  https://github.com/gaiaehr/gaiaehr/commit/bb5b1d6988a7e38dce8bffd7d107e18f61c465b8
