### ISSUE TITLE
Communicate via HL7

### ISSUE THREAD

**Issue by michaelplemmons** [gaiaehr/gaiaehr#48]
I am using version 0.7

I opened a forum topic on the gaiaehr website about this as well.

I am trying to understand how I enable and or use HL7 messaging. I created a site called default and I look at conf.php I see the following.

/**
* HL7 server values
*/
$_SESSION[‘site’][‘hl7′][‘port’] = 9100;

Does this mean that Gaia is listening on port 9100? I do not see port 9100 listening in netstat. If it means that it will send out to an HL7 listener how do I turn it on?

I also notice the hl7_messages and hl7_recipients tables in the MySQL database. What causes those tables to get filled? I have added a patient and do not see anything placed in those tables.

I have found the HL7 server handlers.

https://localhost/gaiaehr/dataProvider/HL7ServerHandler.php?action=start

https://localhost/gaiaehr/dataProvider/HL7ServerHandler.php?action=stop

https://localhost/gaiaehr/dataProvider/HL7ServerHandler.php?action=status

I am able to start the server handler and see it listening on port 9100. I assume this means it is now waiting to HL7 data to be sent to it. Is this correct? How do I make Gaia send to an HL7 server? Also, I see references to a HL7 viewer. How do I access it.

**Comment by andrewbhandari** [comment]
it seems these people are quite busy, no response at all.

**Comment by vela1606** [comment]
Hi there,

The HL7 is a bit complex, what are you trying to achieve?
What messages are you trying to receive and send?

hl7_recipients are the servers/clients data
you can use the Administrator -> HL7 panel to manage this table.

**Comment by michaelplemmons** [comment]
We were trying to get all HL7 messages to be sent out of Gaia.  I was trying to figure out how to turn that on.  However, we have moved in a new direction.  I forgot I had this ticket open so I am going to close it.
