### ISSUE TITLE
unable to Login 

### ISSUE THREAD

**Issue by andrewbhandari** [gaiaehr/gaiaehr#49]
i have Recently download and installed fresh copy of GaiaEHR from Github but the problem is i'm unable to login. i can't even login into it after installation.
when the installation process complete at the last there will appear link to login 
i actually try to login however it keep saying username password invalid 

how am i going to fix this issue, any help please. 
thanks in advance.

**Comment by vela1606** [comment]
HI there,

Few questions...
1. what version are you using?
2. is the user created in the database?

Best regards,
ER

**Comment by andrewbhandari** [comment]
i'm using V1.0.102 
yes i have created user while installing. 

Best Regard. 
Andrew
![np](https://cloud.githubusercontent.com/assets/13488020/10796138/df96f5b8-7dad-11e5-8359-bc5b7e0845ff.png)
![np](https://cloud.githubusercontent.com/assets/13488020/10796153/ebe5f59e-7dad-11e5-8e65-5acdc2c88a7e.png)

**Comment by hrivera787** [comment]
We don't usually work in GitHub Issue System, please go to:
https://gaiaehr.atlassian.net/secure/Dashboard.jspa

Thanks.

**Comment by zeigerpuppy** [comment]
same problem here.
I have tried a number of things, the user is created in the database and matches the username requirement (>3 characters).  There are no special characters in the password.

getting the same error:
The username or password you provided is invalid.

**Comment by xLs** [comment]
Yeah i had to update database user password with generated AES_KEY in config in order to login. so something is going bad at setup.

until fixed.. https://www.tools4noobs.com/online_tools/encrypt/

choose Rijndael-256, ECB and enter the Key (found as session var AES_KEY generated by setup).

enter new pass and update gaiadb user password with mysql
/T

**Comment by hrivera787** [comment]
Hi all;

We have improved the installation process, just **GIT PULL** or download the source code and try it again. Sorry for that.

Gino Rivera Falu
Lead Develope
