### ISSUE TITLE
Patient Search - displayed info

### ISSUE THREAD

**Issue by dom-madrid** [gaiaehr/gaiaehr#5]
Hi,
Test Env.: Ubuntu 14.04 server + Gaiaehr 0.7
Search for patient return some additional info: It would be nice to be able to change the information displayed: i.e. for Spain, time of birth is not really relevant, and SSN is not a used key (at least not a primary one in private clinics). External ID (National ID) would be more relevant in our case.
The DOB does not reflect the date format criteria d-m-Y.

**Comment by vela1606** [comment]
Will look into this... make sense  :+1:
