### ISSUE TITLE
Database tables not created

### ISSUE THREAD

**Issue by zeigerpuppy** [gaiaehr/gaiaehr#51]
On first login, there is an error because the table "geo_ip_location" is not created.
I made a table with a key and two columns "ip_start_num" and "ip_end_num" (MEDIUMINT)
and it seems to suppress the error

**Comment by hrivera787** [comment]
Hi zeigerpuppy;

Thanks for trying GaiaEHR.

We have improved the installation process, just git pull or download the source code, and try it again, we are also automating the database and language compilation. 

Gino Rivera Falu
Lean Developer
