### ISSUE TITLE
Getting Problem to setup this repository with PhpStrom IDE

### ISSUE THREAD

**Issue by ameenalvi** [gaiaehr/gaiaehr#52]
Please provide step to step guidance for development of Gaiaehr 
or submit a part of video of your development and debugging.

**Comment by hrivera787** [comment]
Hi ameenalvi;

Thanks for trying GaiaEHR, we have improved the installation process. We are working on automating the installation package. 

For the development & debugging part, we use Sencha ExtJS framework and our own MicroORM called Matcha::Connect. In the near future we are going to deploy some videos and other things for other to develop. In the mean time we are working on getting the project ONC certified.

Thanks.
Gino Rivera Falu
Lead Developer
