### ISSUE TITLE
Config for compiler 

### ISSUE THREAD

**Issue by gopmarko** [gaiaehr/gaiaehr#54]
Where can I find the config for compiler?

**Comment by hrivera787** [comment]
Hi there;

Sorry for the late response, I had been working on the ONC Certification. 
What do you mean the Config Compiler,?

**Comment by gopmarko** [comment]
Compiling the js and minifying

**Comment by hrivera787** [comment]
Hi there;

This is done using GRUNT, Gruntfile.js in the root directory.
But, for development purpose. We check the IP of the requester.
If the use comes from non-localhost it will give the compiled version,
and if it is localhost it will give the un-compile one.

hope this helps.

On Mon, Mar 14, 2016 at 3:40 PM, gopmarko <notifications@github.com> wrote:

> Compiling the js and minifying
>
> On Monday, March 14, 2016, Gino Rivera <notifications@github.com> wrote:
>
> > Hi there;
> >
> > Sorry for the late response, I had been working on the ONC Certification.
> > What do you mean the Config Compiler,?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/gaiaehr/gaiaehr/issues/54#issuecomment-196477866>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gaiaehr/gaiaehr/issues/54#issuecomment-196490264>.
>



-- 
*Héctor Rivera Falú*

*Senior **Developer* *| The Right Answer, Inc.*
787.275.5120 (w)
hrivera@tranextgen.com


The information contained in this transmission is privileged and
confidential. It is only for use by the intended recipient. If the reader
of this message is not the intended recipient, you are hereby notified that
any dissemination, distribution, or copy of this E-mail is strictly
prohibited. If you received this E-mail in error please notify the sender
promptly by reply E-Mail, then delete this E-Mail, and destroy any copies.

**Comment by vela1606** [comment]
Project moved to [mdtimeline](https://github.com/mdtimeline/mdtimeline)
