### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by websupplements** [gaiaehr/gaiaehr#55]
Facing an error on the first step of installation only. On checking the checkbox and clicking the button, there is a call to 'http://mohit/gaiaehr/data/router.php?site=' and below is the error that is visible in console.

`{"type":"exception","message":"Not Authorized","where":"#0 D:\\Development\\xampp\\htdocs\\gaiaehr\\data
\\router.php(217): doRpc(Object(stdClass))\n#1 {main}"}`

**Comment by Ciscnick** [comment]
Hello, someone could solve the problem of installation step?

**Comment by vela1606** [comment]
Project moved to [mdtimeline](https://github.com/mdtimeline/mdtimeline)
