### ISSUE TITLE
Stuck at Checking compatibility

### ISSUE THREAD

**Issue by kangemi** [gaiaehr/gaiaehr#56]
I am using WAMP Server on a windows 10 x64 pro machine. The installation is stuck at the 2nd step checking compatibility. It is just indicating "loading...". Please assist. This happens on Gaiaehr V1. I have tried version 0.0.7 and its working well. please assist
![gaia](https://cloud.githubusercontent.com/assets/19166019/15784512/852f4a02-29bb-11e6-94d0-1026cda7b099.PNG)

**Comment by mkauzlar** [comment]
same on LAMP (Ubuntu 64bit):
GaiaEHR v1.0.102
Apache 2.4.7
PHP 5.5.9
MariaDB 5.5.49

**Comment by berlstone** [comment]
Same here  with windows 10 x64 pro machine.
Anybody got it working ?

**Comment by kangemi** [comment]
Waiting for assistance on this

**Comment by unixsrv** [comment]
Good  day same problem CentOS 7 x64 LAMP. Please assist.

**Comment by ashishkarpe** [comment]
I am also getting same Issue on windows ec2-instance !!

**Comment by mak1e** [comment]
Hi All, the contributor seems to be very busy and don't have time to support the issues here, website host is also down and redirecting to a domain parking page. 

They are also the same guys manging this site : https://www.mdtimeline.com/

@hrivera787 / @vela1606 , can you help please?

Cheers!

**Comment by zj2050** [comment]
@kangemi @berlstone hi,would you give a link or paper on how to install gaiaehr on win server?
email addr : pub123@126.com
thanks

**Comment by vela1606** [comment]
I am sorry guys!

We are in the middle of the ONC certification. We should be ONC certified by the end of march. After the certification complete, we will help you guys to get started.

Also, mak1e is right we moved to https://github.com/mdtimeline/mdtimeline

**Comment by mkauzlar** [comment]
The same thing happens using the mdtimeline code from: https://github.com/mdtimeline/mdtimeline

**Comment by vela1606** [comment]
Yes, we are aware. We will fix the install after certification.

You won't be able to install the application until we fix this.

**Comment by kimathi** [comment]
How far is the certification please..? Still unable to install

**Comment by cskasun** [comment]
@vela1606 How was your ONC? Hope It was good. We are still waiting for your fixes.

Cheers!

**Comment by hrivera787** [comment]
Hi Kasun;

I don't work on this project anymore.

Sorry.

On Feb 13, 2018 1:11 PM, "Kasun Ranaweera" <notifications@github.com> wrote:

@vela1606 <https://github.com/vela1606> How was your ONC? Hope It was good.
We are still waiting for your fixes.

Cheers!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gaiaehr/gaiaehr/issues/56#issuecomment-365335698>, or mute
the thread

**Comment by cskasun** [comment]
Thank you for your response.
Could you please help me to know this.

![image](https://user-images.githubusercontent.com/35803518/36166225-d21cfd6a-1117-11e8-960a-be3f10a6b74a.png)

why this is happening when I am going to install.

4kasun@gmail.com

**Comment by vela1606** [comment]
Hi @cskasun ,

This project moved to [mdtimeline](https://github.com/mdtimeline/mdtimeline)

although, you experience the same installation error... :-(

I will send you an email to help you.

**Comment by irfanbhatti** [comment]
Dear fellows,
get the right PHP version I used 5.4 on Centos 7
