### ISSUE TITLE
woud anyone give a link how to install gaiaehr on windows server

### ISSUE THREAD

**Issue by zj2050** [gaiaehr/gaiaehr#57]
woud anyone give a link or document how to install gaiaehr on windows server?

email : pub123@126.com

thanks

**Comment by zj2050** [comment]
the link :
http://gaiaehr.org/wamp-and-gaiaehr-installation-windows/
is error

**Comment by vela1606** [comment]
Project moved to [mdtimeline](https://github.com/mdtimeline/mdtimeline)
